# Generated by Django 5.1.4 on 2025-06-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageLeap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='categories',
        ),
        migrations.AlterField(
            model_name='profile',
            name='language_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='LanguageLeap.languagelevel'),
        ),
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.ImageField(blank=True, upload_to='textImage/'),
        ),
        migrations.DeleteModel(
            name='TextCategory',
        ),
    ]
