# Generated by Django 5.1.4 on 2025-06-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageLeap', '0002_remove_text_categories_alter_profile_language_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language_level',
        ),
    ]
